all:
  hosts:
    blog.example.com:
  
  vars:
    # generic infrastructure setting
    fupas_user: root
       
    # ansible configuration
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
  
    # container images
    router_image: eu.gcr.io/fupas-cr/router
    router_version: 1.0.0
    ghost_image: ghost
    ghost_version: 3.39.2
    ghost_port: 2368

    # ghost instance setup
    uid: blog
    hostname: 'blog.example.com'
    mail_from: 'hello@example.com'
    ghost_external_port: 3002
    