
- name: install the official HashiCorp Linux repository
  become: yes
  shell: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

- name: install Hashicorp packages
  become: true
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - nomad
      - consul

- name: create config and data location
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ fupas_user }}"
    group: "{{ fupas_user }}"
  with_list:
    - /opt/config/consul
    - /opt/config/nomad
    - /opt/data/consul
    - /opt/data/nomad
