
- name: create config and data location
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ fupas_user }}"
    group: "{{ fupas_user }}"
  with_list:
    - /opt/config/caddy
    - /opt/data/caddy
    - /opt/data/public

- name: create a default configuration
  template:
    src: ../files/Caddyfile
    dest: /opt/config/caddy/Caddyfile
    owner: "{{ fupas_user }}"
    group: "{{ fupas_user }}"
    mode: '644'
    force: no

- name: create a default static site
  template:
    src: ../files/index.html
    dest: /opt/data/public/index.html
    owner: "{{ fupas_user }}"
    group: "{{ fupas_user }}"
    mode: '644'
    force: no

- name: create router container
  become: true
  shell: >
        docker create --name router --restart always \
        --network n_{{ inventory_hostname }} \
        -v /opt/config:/config -v /opt/data:/data \
        -p 80:80 -p 443:443 \
        {{ router_image }}:{{ router_version }}

