- name: stop router.service
  become: true
  shell: systemctl stop router
  ignore_errors: yes

- name: pull container image
  become: yes
  shell: >
        curl -fsSL https://storage.googleapis.com/fupas-bin/router > /usr/bin/router

        chmod +x /usr/bin/router

- name: create config and data location
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ fupas_user }}"
    group: "{{ fupas_user }}"
  with_list:
    - /opt/config/caddy
    - /opt/data/caddy
    - /opt/data/public

- name: create router.service
  template:
    src: ../files/router.service
    dest: /opt/config/caddy/router.service
    owner: "{{ fupas_user }}"
    group: "{{ fupas_user }}"
    mode: '644'

- name: link router.service
  become: true
  file:
    src: /opt/config/caddy/router.service
    dest: /etc/systemd/system/router.service
    state: link

- name: create a default Caddyfile
  template:
    src: ../files/Caddyfile
    dest: /opt/config/caddy/Caddyfile
    owner: "{{ fupas_user }}"
    group: "{{ fupas_user }}"
    mode: '644'
    force: no

- name: create a default static site
  template:
    src: ../files/index.html
    dest: /opt/data/public/index.html
    owner: "{{ fupas_user }}"
    group: "{{ fupas_user }}"
    mode: '644'
    force: no

- name: enable router.service
  become: true
  shell: >
        systemctl daemon-reload

        systemctl enable router
#
#        systemctl restart router


