
- name: install epel
  become: true
  yum:
    name: "epel-release"
    state: present

- name: install additional packages
  become: true
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - ufw
      - fail2ban

- name: enable fail2ban
  become: true
  shell: >
        systemctl enable fail2ban

        systemctl start fail2ban
        
- name: enable firewall
  become: true
  shell: >
        ufw default deny incoming

        ufw default allow outgoing

        ufw allow from {{ vpc }}

        ufw allow ssh

        ufw allow 80/tcp

        ufw allow 443/tcp

        ufw allow 53/tcp

        ufw allow 53/udp

        ufw --force enable
