
- name: pull image
  become: true
  shell: docker pull {{ ghost_image }}:{{ ghost_version }}
  
- name: create config and data location
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ fupas_user }}"
    group: "{{ fupas_user }}"
  with_list:
    - /opt/data/{{ uid }}

- name: create a default Caddyfile
  template:
    src: ../files/Caddyfile
    dest: /opt/config/caddy/Caddyfile
    owner: "{{ fupas_user }}"
    group: "{{ fupas_user }}"
    mode: '644'
    force: yes

- name: create ghost container
  become: true
  shell: >
        docker create --name ghost-{{ uid }} \
        --restart always \
        --network n_{{ inventory_hostname }} \
        -p {{ ghost_external_port }}:{{ ghost_port }} \
        -v /opt/data/{{ uid }}:/var/lib/ghost/content \
        -e url=http://{{ hostname }} \
        -e mail__from={{ mail_from }}
        {{ ghost_image }}:{{ ghost_version }}
        
- name: start ghost
  become: true
  shell: docker start ghost-{{ uid }}

- name: start the router
  become: true
  shell: docker start router
