#cloud-config
users:
  - name: fupa
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC23WZDHxLWYKJET92y5Lu2m932nUV7h+UhwqUS5h5t8MaZafUD3Q3KxlhPWUNI+n9FR/T1HJ4Sf3QN6ku3WRj2VzZO2VbMe3ljnW2okn8YtQfX7ufPqvjekGL5RzyEj6QbXsln1MIdb/xeq4cyhU+z1KyY8yT3N2Lk64tNIemZyKcLiBObbDwus+6P7NEzkgC8w4C/W5bFbw4kDG4ZHih4bGIQkkAgOTpxoV44STYY1ppke+t0J+gvn+BQcS33AniDt7a1/n4R9btArXzOh7PdInsEfBzwa+7SJEQJuU6J19+h45RZXK9MTHfvhx5uzDaZnO9iyO1ycYrRIZS7YpdcJWHs97Zjwfk/bZXR5h2qSC+0pXWBL0bMlb4wJabJenslLmTN0lE+1cLTMz4eXc2UPwBFBN3lLAJPhG9SLmdmS+Wq6waDQpwCapUKtj+Qwg8xt5luAIo5xoemJHjCWVAOM9p6aDkSzDXHf+tCjp0GjmySVedhZm0WRKm7SPOibMHT2OMSqV6DSuiVFMnztYXLVMcGzWLpiGCVo1oRJbzWVb0SA9II7kiicHjnOiYun1OekEy23yEUZmowcWXjhg1a4gy6nTDNTEVoc3Nw5RwafXJVHxIXxg/YvJh8IjBVsNR9lviFoOZ0axPeG//a3LTfxsyUtAG5YUrFfTdr4Nqs/w== ops@txs.vc
package_update: true
package_upgrade: true
runcmd:
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -i -e '/^PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
  - sed -i -e '/^X11Forwarding/s/^.*$/X11Forwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^#MaxAuthTries/s/^.*$/MaxAuthTries 2/' /etc/ssh/sshd_config
  - sed -i -e '/^#AllowTcpForwarding/s/^.*$/AllowTcpForwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^#AllowAgentForwarding/s/^.*$/AllowAgentForwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^#AuthorizedKeysFile/s/^.*$/AuthorizedKeysFile .ssh/authorized_keys/' /etc/ssh/sshd_config
  - sed -i '$a AllowUsers fupa' /etc/ssh/sshd_config
  - reboot